AWSTemplateFormatVersion: 2010-09-09
Description: Bucket to host well logs and Lambda deployment
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - LambdaPermission
    Properties:
      BucketName: well-logs-cohort-3a-dbf
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .tif
            Function: !GetAtt LambdaFunction.Arn

  DynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: well-logs-cohort-3a-dbf
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 25
        WriteCapacityUnits: 25

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: well-logs-cohort-3a-dbf
      Handler: lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.12
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"status": 200, "message": "hello!"}

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: well-logs-cohort-3a-dbf
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: well-logs-cohort-3a-dbf
      Principal: s3.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:s3:::${ResourceName}'
      SourceAccount: !Ref 'AWS::AccountId'
