AWSTemplateFormatVersion: 2010-09-09
Description: Bucket to host well logs and Lambda deployment
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: well-logs-cohort-3a-dbf
